In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
# load the data
df = pd.read_csv("DS/flic_button_data_export_20251110.csv")

df.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615183,2025-11-10 01:50:40.22+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-60,NaN,60.493152,22.288016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18615186,2025-11-10 01:50:42.122+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.493151,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18615187,2025-11-10 01:50:44.1+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-76,NaN,60.493150,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18615189,2025-11-10 01:50:45.963+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-55,NaN,60.493148,22.288014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18615192,2025-11-10 01:50:48.722+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-54,NaN,60.493146,22.288012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.describe()

,id,ruuvi,companyid,rssi,lat,lon,temperature,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
count,6.842000e+03,0.0,6842.0,6842.000000,6842.000000,6842.000000,6842.000000,6842.000000,6842.000000,6842.000000,6842.000000,6842.0,6842.000000,6842.000000,6842.000000,6842.000000,6842.000000
mean,1.862949e+07,NaN,499.0,-87.993715,60.331300,22.797161,7.372572,588.132710,-684.027477,-10.760012,2.600047,4.0,126.274335,19087.898568,-20.579914,18.857872,0.452239
std,9.218328e+03,NaN,0.0,2.613502,0.194015,0.602762,0.887266,466.654283,228.758490,65.800174,0.057988,0.0,69.063453,8546.316220,64.831436,44.629897,63.313560
min,1.861503e+07,NaN,499.0,-95.000000,59.819417,22.097018,4.780000,-984.000000,-2040.000000,-1128.000000,2.450000,4.0,0.000000,7184.000000,-1115.062094,-534.072002,-1123.722275
25%,1.862030e+07,NaN,499.0,-90.000000,60.204237,22.099120,7.015000,660.000000,-764.000000,-40.000000,2.549000,4.0,68.000000,9985.500000,-35.803199,1.354365,-5.185932
50%,1.863011e+07,NaN,499.0,-88.000000,60.433157,23.044344,7.330000,692.000000,-740.000000,-4.000000,2.619000,4.0,131.000000,20031.500000,-24.037191,18.319635,-0.110021
75%,1.863771e+07,NaN,499.0,-87.000000,60.452013,23.350735,7.930000,972.000000,-408.000000,12.000000,2.658000,4.0,174.000000,26083.000000,-1.732241,34.772237,5.312428
max,1.864457e+07,NaN,499.0,-67.000000,60.502904,23.648723,9.455000,1380.000000,168.000000,1668.000000,2.672000,4.0,254.000000,32688.000000,1733.760877,439.917526,742.479811

In [10]:
# load the data
df = pd.read_csv("DS/g_data_export_20251110.csv")

df.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,NaN,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,NaN,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030