In [1]:
# Import neede libraries for EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load the data
csv_path_1 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20251110.csv"
df1 = pd.read_csv(csv_path_1)

df1.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615183,2025-11-10 01:50:40.22+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-60,NaN,60.493152,22.288016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18615186,2025-11-10 01:50:42.122+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.493151,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18615187,2025-11-10 01:50:44.1+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-76,NaN,60.493150,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18615189,2025-11-10 01:50:45.963+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-55,NaN,60.493148,22.288014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18615192,2025-11-10 01:50:48.722+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-54,NaN,60.493146,22.288012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
csv_path_2 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20251127.csv"
df2 = pd.read_csv(csv_path_2)
df2.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,19073454,2025-11-27 00:06:20.323+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-65,NaN,60.234862,23.588156,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19073455,2025-11-27 00:06:21.841+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-58,NaN,60.235090,23.587418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19073456,2025-11-27 00:06:23.638+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-51,NaN,60.235293,23.586860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19073457,2025-11-27 00:06:25.228+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-65,NaN,60.235455,23.586463,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19073458,2025-11-27 00:06:26.774+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-78,20106.0,60.235624,23.586074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
csv_path_3 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20260109.csv"
df3 = pd.read_csv(csv_path_3)
df3.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,20045549,2026-01-09 01:16:43.519+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-70,NaN,60.463376,22.109561,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20045550,2026-01-09 01:16:45.393+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-59,20106.0,60.463308,22.109523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20045551,2026-01-09 01:16:47.808+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-66,NaN,60.463243,22.109489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20045552,2026-01-09 01:16:50.341+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.463080,22.109335,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20045553,2026-01-09 01:16:52.207+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-61,NaN,60.462975,22.109186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
csv_path_4 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20251110.csv"
df4 = pd.read_csv(csv_path_4)
df4.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,NaN,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,NaN,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

In [6]:
csv_path_5 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20251127.csv"
df5 = pd.read_csv(csv_path_5)
df5.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,19073449,2025-11-27 00:00:05.695+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-87,0201061bff990405fbd6ffffffff0274fd18003470f6f6...,60.197226,23.695725,...,628,-744,52,2.503,4,246,52104,23.731888,-16.938574,41.037724
1,19073450,2025-11-27 00:02:15.075+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405fbcfffffffff022cfd7c00047176e6...,60.210708,23.660503,...,556,-644,4,2.507,4,230,52154,-21.557863,-10.685918,165.125365
2,19073451,2025-11-27 00:03:18.962+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-93,0201061bff990405fbeeffffffff0290fdbcffac71d649...,60.215488,23.638391,...,656,-580,-84,2.510,4,73,52179,-124.335487,94.410635,149.911073
3,19073452,2025-11-27 00:05:26.44+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405fbefffffffff02acfcb4ffd87176f9...,60.232282,23.607309,...,684,-844,-40,2.507,4,249,52229,-67.901596,-52.925755,-68.087101
4,19073453,2025-11-27 00:06:14.015+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-90,0201061bff990405fbfaffffffff025cfd10fffc70163a...,60.234494,23.589772,...,604,-752,-4,2.496,4,58,52248,-28.501015,-47.157435,52.637050

In [7]:
csv_path_6 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20260109.csv"
df6 = pd.read_csv(csv_path_6)
df6.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,20043979,2026-01-09 00:06:10.854+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-87,0201061bff990405f37affffffff02c4fd2000086136de...,60.390492,23.577790,...,708,-736,8,2.377,4,222,56090,-29.688556,42.078561,-4.385111
1,20043980,2026-01-09 00:06:57.334+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f37affffffff02dcfcc0ffc45d362c...,60.392027,23.559964,...,732,-832,-60,2.345,4,44,56108,-94.047775,-11.960919,-90.138394
2,20043981,2026-01-09 00:06:58.861+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f378ffffffff02acfd08ffac5d3632...,60.392055,23.559383,...,684,-760,-84,2.345,4,50,56109,-116.635061,-3.262178,-3.662118
3,20043982,2026-01-09 00:08:24.204+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-88,0201061bff990405f37affffffff02b0fd8c00105f76d7...,60.391609,23.526509,...,688,-628,16,2.363,4,215,56142,-26.005580,99.328246,89.619725
4,20044343,2026-01-09 00:09:21.9+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f377ffffffff0260fcb0ffa45d9641...,60.387343,23.505953,...,608,-848,-92,2.348,4,65,56164,-110.358135,-118.590075,-19.285058

In [8]:
csv_path_7 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20251110.csv"
df7 = pd.read_csv(csv_path_7)
df7.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,43509630,2025-11-10 01:50:38.942+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x90 0...,ab,1,0,20,...,3,3,0.697317,0.340409,0,0,9,8,8862,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
1,43509631,2025-11-10 01:50:38.945+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0xA3 0...,ab,1,0,20,...,3,3,0.697985,0.337601,0,0,9,8,5d4b,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
2,43509632,2025-11-10 01:50:38.947+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x5 0x36 0x0 0x44 0x0 0xB7 0...,ab,1,0,20,...,3,3,0.695922,0.346411,0,0,9,8,c167,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
3,43509633,2025-11-10 01:50:38.949+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x6 0x36 0x0 0x44 0x0 0xCB 0...,ab,1,0,20,...,3,3,0.682641,0.413942,0,0,9,8,2af1,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
4,43509634,2025-11-10 01:50:38.95+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x7 0x36 0x0 0x44 0x0 0xDF 0...,ab,1,0,20,...,3,3,0.683389,0.409591,0,0,9,8,7647,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...

In [9]:
csv_path_8 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20251127.csv"
df8 = pd.read_csv(csv_path_8)
df8.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,47015103,2025-11-27 10:14:51.256+02,Aplicom A11 001,60.386148,23.106956,0xAB 0x1 0x0 0x20 0x0 0x36 0x0 0x44 0x0 0x3F 0...,ab,1,0,20,...,7,11,0.464402,0.0,0.085958,0.000990,9,8,887d,0101000020E6100000691CEA77611B374039B5334C6D31...
1,47015104,2025-11-27 10:14:51.345+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x1 0x36 0x0 0x44 0x0 0x53 0...,ab,1,0,20,...,7,11,0.463235,0.0,0.086225,0.000991,9,8,7315,0101000020E6100000C8242367611B374039B5334C6D31...
2,47015105,2025-11-27 10:14:51.346+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x2 0x36 0x0 0x44 0x0 0x66 0...,ab,1,0,20,...,7,11,0.462989,0.0,0.086281,0.000994,9,8,2fa6,0101000020E6100000C8242367611B374039B5334C6D31...
3,47015106,2025-11-27 10:14:51.741+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x7A 0...,ab,1,0,20,...,7,11,0.463084,0.0,0.086260,0.000990,9,8,23b8,0101000020E6100000C8242367611B374039B5334C6D31...
4,47015107,2025-11-27 10:14:52.204+02,Aplicom A11 001,60.386148,23.106954,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0x8E 0...,ab,1,0,20,...,7,11,0.462395,0.0,0.086418,0.000985,9,8,e3ab,0101000020E6100000282D5C56611B374039B5334C6D31...

In [10]:
csv_path_9 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20260109.csv"
df9 = pd.read_csv(csv_path_9)
df9.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,54179124,2026-01-09 00:00:00.02+02,Aplicom A11 001,60.378603,23.594120,0xAB 0x1 0x0 0x20 0xA5 0x36 0x0 0x44 0x0 0xFC ...,ab,1,0,20,...,7,11,0.136738,0.0,0.287554,0.152802,9,8,c422,0101000020E610000047E6913F18983740709527107630...
1,54179125,2026-01-09 00:00:00.524+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA6 0x36 0x0 0x44 0x0 0x10 ...,ab,1,0,20,...,7,11,0.140446,0.0,0.281358,0.161008,9,8,8c2f,0101000020E6100000A6EECA2E18983740709527107630...
2,54179126,2026-01-09 00:00:01.021+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA7 0x36 0x0 0x44 0x0 0x24 ...,ab,1,0,20,...,7,11,0.138119,0.0,0.285162,0.155872,9,8,0470,0101000020E6100000A6EECA2E18983740709527107630...
3,54179127,2026-01-09 00:00:01.52+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA8 0x36 0x0 0x44 0x0 0x38 ...,ab,1,0,20,...,7,11,0.139221,0.0,0.283298,0.158163,9,8,b268,0101000020E6100000A6EECA2E18983740709527107630...
4,54179128,2026-01-09 00:00:02.021+02,Aplicom A11 001,60.378604,23.594119,0xAB 0x1 0x0 0x20 0xA9 0x36 0x0 0x44 0x0 0x4B ...,ab,1,0,20,...,7,11,0.139290,0.0,0.283283,0.158818,9,8,6502,0101000020E6100000A6EECA2E1898374041118B187630...